# Generated by Django 3.0.2 on 2020-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instakilo', '0002_auto_20200213_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('postid', models.CharField(blank=True, max_length=40, null=True)),
                ('images', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
