# Generated by Django 3.0.2 on 2020-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instakilo', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='dp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
